#SPDX-License-Identifier: MIT-0
---
# vars file for roles/rust-toolchain
version: "1.29.1"
platform: "x86_64-unknown-linux-gnu"
checksum: "sha256:dda7234360b7f578ca8b0ddcb80145646fa61a67c1720a5abc7051b35c9fcb71" # trust on first use
